### ISSUE TITLE
Course can duplicate in case of autoassign after the usage of manual assign

### ISSUE THREAD

**Issue by ArasFirat** [MahmutOzgurKizil/se302-course-scheduler#5]
After allocating a course to a classroom, when  "autoAssign" is used some courses may appear on many different classrooms at the same time.
Cause of issue is probably within the "autoAssign" method. Since the method uses "matchClassroom" function from the database which doesn't prevent duplications.
[IMG_2214.pdf](https://github.com/user-attachments/files/18214432/IMG_2214.pdf)

**Comment by MahmutOzgurKizil** [comment]
Adjusted the code to check if a course is already assigned to a classroom.
